[package]
name = "face-detection"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
image = { workspace = true }
tensorflow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
